[package]
name = "codex-workflow-poc"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"
tar = "0.4"
sha2 = "0.10"
tempfile = "3"
which = "6"

